language: ruby
rvm:
  — 2.5.3
before_install: gem install bundler -v 2.1.2
cache: bundler
bundler_args:
  --without development --jobs=3 --retry=3 --path=../vendor/bundle
script:
  - bundle exec rspec spec
